# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    # Uncomment the following section if you need Bochs or other tools
    #- name: Install Bochs
    #  run: sudo apt-get install -y bochs bochs-sdl bochs-x

    - name: Build Assembly Code
      run: |
        # Adjust the following command based on your build process
        nasm -f bin boot.asm -o boot.bin

    - name: Run Tests
      run: |
        # If you have tests, include commands to run them here
        # For example, you might run your binary in an emulator
        # bochs -q -f bochsrc.txt

    # Optional: Upload artifacts (e.g., built binaries)
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: boot.bin
        path: boot.bin
