# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y nasm qemu-system-x86

    - name: Build Assembly Code
      run: nasm -f bin boot.asm -o boot.bin

    - name: Run in QEMU
      run: |
        # Run the binary in QEMU for a short time
        timeout 5 qemu-system-x86_64 -drive format=raw,file=boot.bin -nographic

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: boot.bin
        path: boot.bin
